-- Explicitly selected by this project's SDDM entry. DMS setup may regenerate
-- its normal config without replacing this file or fedora/*.lua.
local base = assert(os.getenv("XDG_CONFIG_HOME"), "Missing session configuration") .. "/hypr/"
package.path = base .. "?.lua;" .. base .. "?/init.lua;" .. package.path
hl.config({ autogenerated = false })
require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.windowrules")
-- Deliberately do not load dms.binds: our compact map uses DMS IPC directly.
require("dms.binds-user")
hl.on("hyprland.start", function()
    local script = assert(os.getenv("FH_PROJECT_HOME")) .. '/bin/session-start.sh'
    hl.exec_cmd("'" .. script:gsub("'", "'\\''") .. "'")
end)
